// Copies the lucide-static sprite to the panel runtime (web/panel/icons.svg)
// and regenerates spriteIconNames.ts from its symbol ids, so the icon picker
// can only offer names the panel can actually render. The panel resolves
// icons by direct sprite lookup (icons.svg#<name>); deriving the picker list
// from anything else (e.g. lucide-react's PascalCase exports) drifts from the
// sprite ids. Runs as part of `npm run build`.
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const programmerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const spritePath = path.join(programmerRoot, "node_modules", "lucide-static", "sprite.svg");
const sprite = readFileSync(spritePath, "utf8");

const names = [...sprite.matchAll(/<symbol[^>]*\bid="([^"]+)"/g)].map((m) => m[1]).sort();
if (names.length < 500) {
  throw new Error(`only ${names.length} symbol ids found in ${spritePath} — sprite format changed?`);
}

copyFileSync(spritePath, path.join(programmerRoot, "..", "panel", "icons.svg"));

const outPath = path.join(
  programmerRoot, "src", "components", "ui-builder", "spriteIconNames.ts",
);
const header =
  "// Generated by scripts/build-icons.mjs from lucide-static/sprite.svg — do not edit.\n" +
  "// Symbol ids of the sprite the panel runtime renders icons from\n" +
  "// (web/panel/icons.svg); the icon picker only offers names on this list.\n";
writeFileSync(outPath, `${header}export const SPRITE_ICON_NAMES: string[] = ${JSON.stringify(names, null, 2)};\n`);
console.log(`build-icons: copied sprite and wrote ${names.length} icon names`);
