"""Regression tests for the macro Convert-to-Script generator (macroHelpers.ts).

The generator runs in the Programmer IDE, so the scenarios are generated by
bundling the real macroHelpers.ts with the esbuild already in
openavc/web/programmer/node_modules (tests/fixtures/macro_helpers_harness.cjs) — then
the generated Python is compiled and EXECUTED here against a stubbed `openavc`
module whose ``compare`` is the real ``openavc.core.script_api.compare``. That
closes the loop: the generated code is proven to run, and to match the macro
engine's semantics (shared condition coercion, $-reference resolution,
offline guards), not just to look plausible. Skips when the Node toolchain is
absent rather than failing the Python-only CI gate.

Covers the audit findings fixed in the macroHelpers.ts group:
  comparisons route through compare() so string-stored numerics behave like
  the macro engine instead of raising TypeError; trigger/cron/name/id text is
  escaped so hostile values can't break or break OUT of the generated source;
  $-params resolve via state.get() like the engine (and payloads stay
  verbatim, also like the engine); JS true/false/null become Python literals;
  device.command honors skip_if_offline and group.command skips offline
  members.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import shutil
import subprocess
import sys
import types
from pathlib import Path

import pytest

from tests import gates

from openavc.core.condition_eval import eval_operator
from openavc.core.script_api import compare as script_compare

OPENAVC_ROOT = Path(__file__).resolve().parents[1]

HARNESS = OPENAVC_ROOT / "tests" / "fixtures" / "macro_helpers_harness.cjs"
HELPERS = (
    OPENAVC_ROOT / "openavc" / "web" / "programmer" / "src" / "components" / "macros" / "macroHelpers.ts"
)
NODE_MODULES = OPENAVC_ROOT / "openavc" / "web" / "programmer" / "node_modules"
ESBUILD_DIR = NODE_MODULES / "esbuild"


def _toolchain_reason() -> str | None:
    if shutil.which("node") is None:
        return "node not installed"
    if not ESBUILD_DIR.is_dir():
        return "esbuild not installed (run `npm ci` in openavc/web/programmer)"
    if not HARNESS.is_file():
        return "macro helpers harness missing"
    if not HELPERS.is_file():
        return "macroHelpers.ts missing"
    return None


@pytest.fixture(scope="module")
def generated() -> dict:
    reason = _toolchain_reason()
    if reason:
        gates.skip_or_fail(gates.NODE, reason)
    proc = subprocess.run(
        ["node", str(HARNESS), str(HELPERS)],
        capture_output=True,
        text=True,
        cwd=str(OPENAVC_ROOT),
        env={**os.environ, "NODE_PATH": str(NODE_MODULES)},
        timeout=120,
    )
    if proc.returncode != 0:
        raise AssertionError(
            f"macro helpers harness crashed (rc={proc.returncode}):\n{proc.stderr}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive
        raise AssertionError(
            f"could not parse harness output:\n{proc.stdout}\n---\n{proc.stderr}"
        ) from exc


# --- Stubbed `openavc` runtime for executing generated scripts ---


class _StubState:
    def __init__(self, data: dict | None = None):
        self.data = dict(data or {})

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value, source="script"):
        self.data[key] = value


class _StubDevices:
    def __init__(self):
        self.sent: list[tuple] = []

    async def send(self, device_id, command, params=None):
        self.sent.append((device_id, command, params))


class _StubEvents:
    def __init__(self):
        self.emitted: list[tuple] = []

    async def emit(self, name, payload=None):
        self.emitted.append((name, payload))


class _StubMacros:
    def __init__(self):
        self.executed: list[str] = []

    async def execute(self, macro_id):
        self.executed.append(macro_id)


class _ExecResult:
    def __init__(self, ns, state, devices, events, macros, state_handlers, event_handlers):
        self.ns = ns
        self.state = state
        self.devices = devices
        self.events = events
        self.macros = macros
        self.state_handlers = state_handlers
        self.event_handlers = event_handlers

    def run(self):
        asyncio.run(self.ns["run"]())


def _exec_script(source: str, state: dict | None = None) -> _ExecResult:
    """Compile + exec a generated script against a stubbed openavc module."""
    mod = types.ModuleType("openavc")
    st = _StubState(state)
    dv = _StubDevices()
    ev = _StubEvents()
    mc = _StubMacros()
    state_handlers: list[tuple] = []
    event_handlers: list[tuple] = []

    def on_state_change(pattern):
        def deco(fn):
            state_handlers.append((pattern, fn))
            return fn
        return deco

    def on_event(pattern):
        def deco(fn):
            event_handlers.append((pattern, fn))
            return fn
        return deco

    mod.state = st
    mod.devices = dv
    mod.events = ev
    mod.macros = mc
    mod.log = logging.getLogger("test.generated_script")
    mod.compare = script_compare  # the real shared evaluator
    mod.on_state_change = on_state_change
    mod.on_event = on_event

    code = compile(source, "<generated>", "exec")
    ns: dict = {}
    # Shadow the real package while the generated script runs, so `from openavc
    # import ...` binds these fakes. Restore it afterwards rather than deleting:
    # `openavc` is the shipped package now, and dropping it from sys.modules
    # leaves every later import in this process building a second, unrelated
    # module object.
    _real_openavc = sys.modules.get("openavc")
    sys.modules["openavc"] = mod
    try:
        exec(code, ns)
    finally:
        if _real_openavc is not None:
            sys.modules["openavc"] = _real_openavc
        else:
            del sys.modules["openavc"]
    return _ExecResult(ns, st, dv, ev, mc, state_handlers, event_handlers)


SCENARIOS = [
    "coercion_conditional",
    "coercion_wait_until",
    "injection",
    "dollar_params",
    "python_literals",
    "skip_if_offline",
    "group_offline",
    "skip_if_alias",
    "trigger_gte",
    "wait_until_timeout_fail",
    "legacy_plain",
]


@pytest.mark.parametrize("scenario", SCENARIOS)
def test_generated_script_compiles(generated: dict, scenario: str) -> None:
    """Every generated script must be syntactically valid Python."""
    assert scenario in generated, f"harness did not report {scenario}"
    compile(generated[scenario]["script"], f"<{scenario}>", "exec")


class TestComparisonCoercion:
    """Generated conditions must behave like the macro engine's evaluator."""

    def test_conditional_matches_string_stored_numeric(self, generated):
        r = _exec_script(generated["coercion_conditional"]["script"],
                         {"var.level": "75"})
        r.run()
        assert r.devices.sent == [("ok_dev", "go", None)]

    def test_conditional_type_mismatch_takes_else_branch(self, generated):
        # Empty string vs 50: the engine yields False (no TypeError) -> else
        r = _exec_script(generated["coercion_conditional"]["script"],
                         {"var.level": ""})
        r.run()
        assert r.devices.sent == [("else_dev", "halt", None)]

    def test_wait_until_satisfied_by_string_stored_numeric(self, generated):
        r = _exec_script(generated["coercion_wait_until"]["script"],
                         {"var.temp": "65"})
        r.run()  # would hang/raise if the comparison misbehaved
        assert r.devices.sent == [("after_dev", "done", None)]

    def test_wait_until_timeout_fail_raises(self, generated):
        r = _exec_script(generated["wait_until_timeout_fail"]["script"],
                         {"var.never": "no"})
        with pytest.raises(TimeoutError):
            r.run()

    def test_skip_if_alias_operator_evaluates(self, generated):
        # ">=" alias + string-stored numeric: 3 >= 2 -> step skipped
        r = _exec_script(generated["skip_if_alias"]["script"], {"var.mode": "3"})
        r.run()
        assert r.devices.sent == []
        # 1 >= 2 is False -> step runs
        r2 = _exec_script(generated["skip_if_alias"]["script"], {"var.mode": "1"})
        r2.run()
        assert r2.devices.sent == [("guarded", "cmd", None)]

    def test_trigger_operator_check_coerces(self, generated):
        r = _exec_script(generated["trigger_gte"]["script"])
        assert len(r.state_handlers) == 1
        pattern, handler = r.state_handlers[0]
        assert pattern == "var.x"
        # String-stored 75 >= 50 -> steps run
        asyncio.run(handler("var.x", None, "75"))
        assert r.devices.sent == [("trig_dev", "fire", None)]
        # String-stored 25 >= 50 -> guard returns early
        r.devices.sent.clear()
        asyncio.run(handler("var.x", None, "25"))
        assert r.devices.sent == []


class TestEscaping:
    """Hostile macro text must stay inert and round-trip exactly."""

    def test_hostile_fields_compile_and_round_trip(self, generated):
        entry = generated["injection"]
        src = entry["script"]
        meta = entry["meta"]
        r = _exec_script(src)

        # No interpolated text escaped into a real import statement
        for line in src.splitlines():
            assert not re.match(r"^\s*import\s+os\b", line), line

        # Decorator patterns round-trip to the exact literal values
        state_patterns = [p for p, _ in r.state_handlers]
        event_patterns = [p for p, _ in r.event_handlers]
        assert state_patterns == [meta["state_key"]]
        assert meta["event_pattern"] in event_patterns
        assert meta["schedule_pattern"] in event_patterns

    def test_docstring_survives_hostile_name(self, generated):
        entry = generated["injection"]
        r = _exec_script(entry["script"])
        # The module docstring exists and still contains the macro name's
        # hostile characters as text
        assert r.ns["__doc__"] is not None
        assert '"""' in r.ns["__doc__"]
        assert "Room" in r.ns["__doc__"]


class TestValueGeneration:
    """$-references and JS literals must translate like the macro engine."""

    def test_dollar_params_resolve_via_state(self, generated):
        r = _exec_script(generated["dollar_params"]["script"], {
            "var.preset": 7,
            "var.src": "cam1",
            "device.d_on.connected": True,
            "device.d_off.connected": True,
        })
        r.run()
        # device.command params: $var.preset resolved, static passthrough
        assert r.devices.sent[0] == ("proj", "set_preset", {"level": 7, "static": 5})
        # state.set value resolved
        assert r.state.data["var.active_source"] == "cam1"
        # event payload NOT resolved (macro engine passes payloads verbatim)
        assert r.events.emitted == [("source.changed", {"ref": "$var.src", "n": 1})]
        # group.command params resolved for each member
        group_sends = [s for s in r.devices.sent if s[1] == "gcmd"]
        assert group_sends == [
            ("d_on", "gcmd", {"p": 7}),
            ("d_off", "gcmd", {"p": 7}),
        ]

    def test_js_literals_become_python_literals(self, generated):
        r = _exec_script(generated["python_literals"]["script"])
        r.run()
        assert r.devices.sent == [(
            "amp", "cfg",
            {"mute": True, "label": None, "nested": {"a": [True, None, "x"]}, "f": 1.5},
        )]

    def test_legacy_plain_macro_unchanged_behavior(self, generated):
        r = _exec_script(generated["legacy_plain"]["script"])
        r.run()
        assert ("disp", "input_hdmi1", None) in r.devices.sent
        assert r.state.data["var.src"] == "hdmi1"
        assert r.macros.executed == ["sub_macro"]


class TestOfflineGuards:
    """Generated scripts must honor the engine's offline-skip behavior."""

    def test_skip_if_offline_guard(self, generated):
        r = _exec_script(generated["skip_if_offline"]["script"],
                         {"device.dev_off.connected": False})
        r.run()
        # Guarded step skipped; unguarded step still sends (engine parity)
        assert r.devices.sent == [("dev_off", "cmd2", None)]

    def test_skip_if_offline_sends_when_connected(self, generated):
        r = _exec_script(generated["skip_if_offline"]["script"],
                         {"device.dev_off.connected": True})
        r.run()
        assert r.devices.sent == [
            ("dev_off", "cmd1", None),
            ("dev_off", "cmd2", None),
        ]

    def test_group_command_skips_offline_members(self, generated):
        r = _exec_script(generated["group_offline"]["script"], {
            "device.d_on.connected": True,
            "device.d_off.connected": False,
        })
        r.run()
        assert r.devices.sent == [("d_on", "power_on", None)]


class TestCompareExport:
    """`compare` is exported from the script API and matches eval_operator."""

    def test_compare_semantics(self):
        assert script_compare("75", "gte", 50) is True
        assert script_compare(5, "eq", "5") is True
        assert script_compare(None, "gt", 1) is False
        assert script_compare("x", "gt", 1) is False  # mismatch -> False, no raise
        assert script_compare(1, "truthy") is True
        assert script_compare("", "falsy") is True
        assert script_compare("3", ">=", 2) is True  # alias normalization

    def test_compare_delegates_to_shared_evaluator(self):
        for op, actual, target in [
            ("eq", "on", "on"), ("ne", 1, 2), ("gte", "10", 10), ("lt", 3, "4"),
        ]:
            assert script_compare(actual, op, target) == eval_operator(op, actual, target)
