"""Regression tests for the System Log Device filter (logViewHelpers.ts).

The old filter matched device ids against the logger module name
(e.source), where device ids never appear — selecting a device blanked the
log. The filter now matches the structured device field the server extracts
from "[id] "-prefixed driver/transport lines (log_buffer.py, covered in
test_log_buffer.py), with a whole-token message fallback for device_manager
lifecycle lines that phrase the id loosely.

The predicate runs in the Programmer IDE, so the verdicts are generated by
bundling the real logViewHelpers.ts with the esbuild already in
web/programmer/node_modules (tests/fixtures/log_view_helpers_harness.cjs).
Skips when the Node toolchain is absent rather than failing the Python-only
CI gate.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tests import gates

OPENAVC_ROOT = Path(__file__).resolve().parents[1]

HARNESS = OPENAVC_ROOT / "tests" / "fixtures" / "log_view_helpers_harness.cjs"
HELPERS = OPENAVC_ROOT / "web" / "programmer" / "src" / "views" / "logViewHelpers.ts"
NODE_MODULES = OPENAVC_ROOT / "web" / "programmer" / "node_modules"
ESBUILD_DIR = NODE_MODULES / "esbuild"

EXPECTED = {
    # Structured device field (extracted server-side from "[id] " prefixes)
    "structured_match": True,
    "structured_other_device": False,
    "structured_case_insensitive": True,
    # Whole-token message mentions (device_manager lifecycle phrasing)
    "mention_quoted": True,
    "mention_bare": True,
    "mention_state_key": True,
    "mention_end_of_message": True,
    # Non-matches: unrelated lines and near-miss ids
    "no_mention": False,
    "substring_longer_id": False,
    "substring_prefixed_id": False,
    "id_with_underscore": True,
}


def _toolchain_reason() -> str | None:
    if shutil.which("node") is None:
        return "node not installed"
    if not ESBUILD_DIR.is_dir():
        return "esbuild not installed (run `npm ci` in web/programmer)"
    if not HARNESS.is_file():
        return "log view helpers harness missing"
    if not HELPERS.is_file():
        return "logViewHelpers.ts missing"
    return None


@pytest.fixture(scope="module")
def verdicts() -> dict[str, bool]:
    reason = _toolchain_reason()
    if reason:
        gates.skip_or_fail(gates.NODE, reason)
    proc = subprocess.run(
        ["node", str(HARNESS), str(HELPERS)],
        capture_output=True,
        text=True,
        cwd=str(OPENAVC_ROOT),
        env={**os.environ, "NODE_PATH": str(NODE_MODULES)},
        timeout=120,
    )
    if proc.returncode != 0:
        raise AssertionError(
            f"log view helpers harness crashed (rc={proc.returncode}):\n{proc.stderr}"
        )
    return json.loads(proc.stdout)


def test_scenarios_covered(verdicts):
    assert set(verdicts) == set(EXPECTED)


@pytest.mark.parametrize("scenario", sorted(EXPECTED))
def test_device_filter(verdicts, scenario):
    assert verdicts[scenario] is EXPECTED[scenario], (
        f"{scenario}: expected {EXPECTED[scenario]}, got {verdicts[scenario]}"
    )
